# Generated by Django 2.0.2 on 2018-02-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Feedback'},
        ),
    ]
