# Generated by Django 2.0.2 on 2018-02-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Doc',
        ),
    ]
