# Generated by Django 2.0.2 on 2018-02-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_auto_20180222_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='url',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shortener.URL'),
        ),
    ]
