# Generated by Django 2.0.2 on 2018-02-22 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_auto_20180222_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='url',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='shortener.URL'),
            preserve_default=False,
        ),
    ]
