# Generated by Django 2.0.2 on 2018-02-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_doc_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='user',
        ),
    ]
