# Generated by Django 2.0.2 on 2018-02-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
